### ISSUE TITLE
last-modified datetime in CMS_ARS_5_0.json is malformed

### ISSUE THREAD

**Issue by GaryGapinski** [CMSgov/ars-machine-readable#11]
Has a space (U+0020) rather than T (U+0054) between date and time (line 6 `"last-modified": "2022-02-11 14:29:58.030514-06:00"`).

The [OSCAL schema](https://pages.nist.gov/OSCAL/reference/latest/complete/json-reference/#/catalog/metadata/last-modified) specifies RFC 3339 format (essentially ISO 8601).

**Comment by openprivacy** [comment]
Fixed. See https://raw.githubusercontent.com/CMSgov/ars-machine-readable/main/5.0/oscal/json/CMS_ARS_5_0_catalog.json

Also, the files in https://github.com/CMSgov/ars-machine-readable/tree/main/5.0/oscal/json will soon be replaced by resolved catalogs generated directly from NIST SP 800-53r5
